name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.UBUNTU_HOSTNAME }}
          username: ubuntu
          key: ${{ secrets.UBUNTU_PRIVATE_KEY }}
          script: |
            # 1. Update and install prerequisites
            sudo apt update
            sudo apt install -y curl git build-essential

            # 2. Install nvm
            if [ ! -d "$HOME/.nvm" ]; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            fi
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # 3. Install Node 20 via nvm
            nvm install 20
            nvm use 20

            # 4. Install global tools pnpm and pm2
            npm install -g pnpm pm2

            # 5. Clone repo if not exists, else pull latest
            if [ ! -d "/home/ubuntu/devops-deploy" ]; then
              git clone https://github.com/Tejas-pr/devops-deploy.git /home/ubuntu/devops-deploy
            fi
            cd /home/ubuntu/devops-deploy
            git pull origin main

            # 6. Install dependencies, build, and run app
            pnpm install
            pnpm run build
            pm2 restart vite-app || pm2 start "pnpm run preview -- --host 0.0.0.0 --port 4173" --name vite-app
