name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.UBUNTU_HOSTNAME }}
          username: ubuntu
          key: ${{ secrets.UBUNTU_PRIVATE_KEY }}
          script: |
            # -----------------------------
            # 1. Install prerequisites if missing
            # -----------------------------
            command -v curl >/dev/null 2>&1 || sudo apt update && sudo apt install -y curl git build-essential

            # -----------------------------
            # 2. Install NVM if missing
            # -----------------------------
            if [ ! -d "$HOME/.nvm" ]; then
              echo "Installing NVM..."
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            fi
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # -----------------------------
            # 3. Install Node 20 if missing
            # -----------------------------
            if ! command -v node >/dev/null 2>&1 || [ "$(node -v | cut -d v -f2 | cut -d. -f1)" -ne 20 ]; then
              echo "Installing Node 20..."
              nvm install 20
              nvm use 20
            fi

            # -----------------------------
            # 4. Install PNPM and PM2 if missing
            # -----------------------------
            command -v pnpm >/dev/null 2>&1 || npm install -g pnpm
            command -v pm2 >/dev/null 2>&1 || npm install -g pm2

            # -----------------------------
            # 5. Pull latest code
            # -----------------------------
            cd /home/ubuntu/devops-deploy || exit
            if [ ! -d ".git" ]; then
              git clone https://github.com/Tejas-pr/devops-deploy.git .
            else
              git pull origin main
            fi

            # -----------------------------
            # 6. Install dependencies, build and restart
            # -----------------------------
            pnpm install --frozen-lockfile
            pnpm run build
            pm2 restart vite-app || pm2 start "pnpm run preview -- --host 0.0.0.0 --port 4173" --name vite-app
